name: Continuous Integration

on:
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check if organization member
        id: check_org_member
        uses: Mind-Sports-Games/check-org-member@v1.1.0
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Failed
        if: ${{ steps.check_org_member.outputs.result == 'false' }}
        run: |
          echo User Does Not Belong to Mind-Sports-Games
          exit 1
      - name: Check Passed
        run: echo The actor is an organization member
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup JVM
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Test
        run: sbt test 

  compile:
    runs-on: ubuntu-20.04
    steps:
      - name: Check if organization member
        id: check_org_member
        uses: Mind-Sports-Games/check-org-member@v1.1.0
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Failed
        if: ${{ steps.check_org_member.outputs.result == 'false' }}
        run: |
          echo User Does Not Belong to Mind-Sports-Games
          exit 1
      - name: Check Passed
        run: echo The actor is an organization member
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup JVM
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: compile
        run: sbt compile 

  format:
    runs-on: ubuntu-20.04
    steps:
      - name: Check if organization member
        id: check_org_member
        uses: Mind-Sports-Games/check-org-member@v1.1.0
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Failed
        if: ${{ steps.check_org_member.outputs.result == 'false' }}
        run: |
          echo User Does Not Belong to Mind-Sports-Games
          exit 1
      - name: Check Passed
        run: echo The actor is an organization member
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup JVM
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Check Formatting
        run: sbt scalafmt
